name: Cucumber Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: npm run build     

    - name: Use Stable oscal
      run: node ./dist/cli.js use latest

    - name: Update Server
      run: node ./dist/cli.js server update

    - name: Start Server
      run: node ./dist/cli.js server start&

    - name: Run Cucumber tests
      run: npm run test

