name: Generate Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install cli
      run: npm install oscal -g

    - name: produce artifacts in all formats
      run: oscal convert -f ./src/content/rev5/baselines/xml -o artifacts

    - name: produce artifacts for ssp
      run: oscal convert -f ./src/content/rev5/templates/ssp/xml -o artifacts/content/templates/ssp
    - name: produce artifacts for poam
      run: oscal convert -f ./src/content/rev5/templates/poam/xml -o artifacts/content/templates/poam
    - name: produce artifacts for sap
      run: oscal convert -f ./src/content/rev5/templates/sap/xml -o artifacts/content/templates/sap
    - name: produce artifacts for sar
      run: oscal convert -f ./src/content/rev5/templates/sar/xml -o artifacts/content/templates/sar
    - name: Resolve FedRAMP HIGH baseline profile
      run: oscal resolve -f ./src/content/rev5/baselines/xml/FedRAMP_rev5_HIGH-baseline_profile.xml -o ./artifacts/xml/FedRAMP_rev5_HIGH-baseline-resolved-profile_catalog.xml

    - name: Resolve FedRAMP MODERATE baseline profile
      run: oscal resolve -f ./src/content/rev5/baselines/xml/FedRAMP_rev5_MODERATE-baseline_profile.xml -o ./artifacts/xml/FedRAMP_rev5_MODERATE-baseline-resolved-profile_catalog.xml

    - name: Resolve FedRAMP LOW baseline profile
      run: oscal resolve -f ./src/content/rev5/baselines/xml/FedRAMP_rev5_LOW-baseline_profile.xml -o ./artifacts/xml/FedRAMP_rev5_LOW-baseline-resolved-profile_catalog.xml

    - name: Resolve FedRAMP LI-SaaS baseline profile
      run: oscal resolve -f ./src/content/rev5/baselines/xml/FedRAMP_rev5_LI-SaaS-baseline_profile.xml -o ./artifacts/xml/FedRAMP_rev5_LI-SaaS-baseline-resolved-profile_catalog.xml

    - name: Convert FedRAMP HIGH resolved profile to JSON
      run: oscal convert -f ./artifacts/json/FedRAMP_rev5_HIGH-baseline-resolved-profile_catalog.json -o ./artifacts/json/FedRAMP_rev5_HIGH-baseline-resolved-profile_catalog.json

    - name: Convert FedRAMP MODERATE resolved profile to JSON
      run: oscal convert -f ./artifacts/json/FedRAMP_rev5_MODERATE-baseline-resolved-profile_catalog.xml -o ./artifacts/json/FedRAMP_rev5_MODERATE-baseline-resolved-profile_catalog.json

    - name: Convert FedRAMP LOW resolved profile to JSON
      run: oscal convert -f ./artifacts/json/FedRAMP_rev5_LOW-baseline-resolved-profile_catalog.xml -o ./artifacts/json/FedRAMP_rev5_LOW-baseline-resolved-profile_catalog.json

    - name: Convert FedRAMP LI-SaaS resolved profile to JSON
      run: oscal convert -f ./artifacts/json/FedRAMP_rev5_LI-SaaS-baseline-resolved-profile_catalog.xml -o ./artifacts/json/FedRAMP_rev5_LI-SaaS-baseline-resolved-profile_catalog.json

    - name: Convert FedRAMP HIGH resolved profile to YAML
      run: oscal convert -f ./artifacts/json/FedRAMP_rev5_HIGH-baseline-resolved-profile_catalog.xml -o ./artifacts/yaml/FedRAMP_rev5_HIGH-baseline-resolved-profile_catalog.yaml

    - name: Convert FedRAMP MODERATE resolved profile to YAML
      run: oscal convert -f ./artifacts/json/FedRAMP_rev5_MODERATE-baseline-resolved-profile_catalog.xml -o ./artifacts/yaml/FedRAMP_rev5_MODERATE-baseline-resolved-profile_catalog.yaml

    - name: Convert FedRAMP LOW resolved profile to YAML
      run: oscal convert -f ./artifacts/json/FedRAMP_rev5_LOW-baseline-resolved-profile_catalog.xml -o ./artifacts/yaml/FedRAMP_rev5_LOW-baseline-resolved-profile_catalog.yaml

    - name: Convert FedRAMP LI-SaaS resolved profile to YAML
      run: oscal convert -f ./artifacts/json/FedRAMP_rev5_LI-SaaS-baseline-resolved-profile_catalog.xml -o ./artifacts/yaml/FedRAMP_rev5_LI-SaaS-baseline-resolved-profile_catalog.yaml
    - name: Generate Cucumber HTML report
      run: |
        npm run report
        mv cucumber-report.html ./artifacts/cucumber-report.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./artifacts
        publish_branch: gh-pages
        keep_files: false