name: Generate Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
    HOME_REPO: GSA/oscal-js
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install cli
      run: npm install oscal -g

    - name: Produce artifacts baselines in all formats
      run: oscal convert -f ./content/rev5/baselines/xml -o artifacts/content/rev5/baselines/
    - name: Produce artifacts for ssp
      run: oscal convert -f ./content/rev5/templates/ssp/xml -o artifacts/content/rev5/templates/ssp
    - name: Produce artifacts for poam
      run: oscal convert -f ./content/rev5/templates/poam/xml -o artifacts/content/rev5/templates/poam
    - name: Produce artifacts for sap
      run: oscal convert -f ./content/rev5/templates/sap/xml -o artifacts/content/rev5/templates/sap
    - name: Produce artifacts for sar
      run: oscal convert -f ./content/rev5/templates/sar/xml -o artifacts/content/rev5/templates/sar

    - name: Resolve FedRAMP HIGH baseline profile
      run: oscal resolve -f ./content/rev5/baselines/xml/FedRAMP_rev5_HIGH-baseline_profile.xml -o ./artifacts/content/rev5/baselines/xml/FedRAMP_rev5_HIGH-baseline-resolved-profile_catalog.xml

    - name: Resolve FedRAMP MODERATE baseline profile
      run: oscal resolve -f ./content/rev5/baselines/xml/FedRAMP_rev5_MODERATE-baseline_profile.xml -o ./artifacts/content/rev5/baselines/xml/FedRAMP_rev5_MODERATE-baseline-resolved-profile_catalog.xml

    - name: Resolve FedRAMP LOW baseline profile
      run: oscal resolve -f ./content/rev5/baselines/xml/FedRAMP_rev5_LOW-baseline_profile.xml -o ./artifacts/content/rev5/baselines/xml/FedRAMP_rev5_LOW-baseline-resolved-profile_catalog.xml

    - name: Resolve FedRAMP LI-SaaS baseline profile
      run: oscal resolve -f ./content/rev5/baselines/xml/FedRAMP_rev5_LI-SaaS-baseline_profile.xml -o ./artifacts/content/rev5/baselines/xml/FedRAMP_rev5_LI-SaaS-baseline-resolved-profile_catalog.xml

    - name: Convert Profiles to JSON
      run: oscal convert -f ./artifacts/content/rev5/baselines/xml/ -o ./artifacts/content/rev5/baselines/json/ -t JSON

    - name: Convert Profiles to YAML
      run: oscal convert -f ./artifacts/content/rev5/baselines/xml/ -o ./artifacts/content/rev5/baselines/yaml/ -t YAML

    - name: Validate all output recursively
      run: oscal validate -f ./artifacts/ -e fedramp -r

    - name: Deploy to GitHub Pages (forks only)
      uses: peaceiris/actions-gh-pages@v3
      if: github.repository != env.HOME_REPO && github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./artifacts
        publish_branch: gh-pages
        keep_files: false