name: Publish to NPM

on:
  push:
    branches: [main]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify NPM_TOKEN secret
        run: |
          if [ -z "$NODE_AUTH_TOKEN" ]; then
            echo "ERROR: NODE_AUTH_TOKEN is not set"
            exit 1
          else
            echo "NODE_AUTH_TOKEN is set and its length is ${#NODE_AUTH_TOKEN} characters"
          fi
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      
      - name: Configure npm
        run: npm config set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Build (if needed)
        run: npm run build
      
      - name: Publish to NPM
        run: npm publish