name: Publish to NPM

on:
  push:
    branches: [main]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      
      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
      
      - name: Install dependencies
        run: npm ci
            
      - name: Build (if needed)
        run: npm run build
      
      - name: Publish to NPM
        run: npm publish