name: Windows Support

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm i 
    - name: Install tsc
      run: npm install --save-dev typescript
    
    - name: Build javacsript distribution
      run: npm run build

    - name: Resolve FedRAMP HIGH baseline profile
      run: node ./dist/cli.js resolve -f ./content/rev5/baselines/xml/FedRAMP_rev5_HIGH-baseline_profile.xml -o ./artifacts/content/rev5/baselines/xml/FedRAMP_rev5_HIGH-baseline-resolved-profile_catalog.xml

    - name: Convert Profiles to JSON
      run: node ./dist/cli.js convert ./artifacts/content/rev5/baselines/xml/ -o ./artifacts/content/rev5/baselines/json/ -t JSON

    - name: Convert Profiles to YAML
      run: node ./dist/cli.js convert ./artifacts/content/rev5/baselines/xml/ -o ./artifacts/content/rev5/baselines/yaml/ -t YAML

    - name: Validate all output recursively
      run: node ./dist/cli.js validate -f ./artifacts/ -e fedramp -r
